name: Kamu Ilan Tarayici

on:
  schedule:
    # Her gün Türkiye saatiyle sabah 09:00 ve akşam 18:00'de çalışır
    - cron: '0 6,15 * * *'
  workflow_dispatch: # Elle tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 urllib3 pypdf

    - name: Tarayıcıyı Çalıştır
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
